Vagrant.configure("2") do |config|
  # Configuración para los dos servidores web con Apache
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/bionic64"
    web1.vm.network "private_network", ip: "192.168.33.10" # IP estática
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

    # Instalación y configuración de Apache
    web1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl enable apache2
      sudo systemctl start apache2
    SHELL
  end

  # Configuración para el segundo servidor web con Apache
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/bionic64"
    web2.vm.network "private_network", ip: "192.168.33.11" # IP estática
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

    # Instalación y configuración de Apache
    web2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl enable apache2
      sudo systemctl start apache2
    SHELL
  end

  # Configuración para el servidor de balanceo de carga con Nginx
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/bionic64"
    nginx.vm.network "private_network", ip: "192.168.33.12" # IP estática
    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

    # Instalación y configuración de Nginx para el balanceo de carga
    nginx.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
      sudo systemctl enable nginx
      sudo systemctl start nginx

      # Configuración de Nginx para balanceo de carga
      sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
      upstream backend {
        server 192.168.33.10;
        server 192.168.33.11;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://backend;
          proxy_set_header Host \$host;
          proxy_set_header X-Real-IP \$remote_addr;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto \$scheme;
        }
      }
      EOT

      # Reiniciar Nginx para aplicar la nueva configuración
      sudo systemctl restart nginx
    SHELL
  end
end

